### PR TITLE
Remove .DS_Store file

### PR DESCRIPTION
**Pull request by maxwang096**
#### What problem does your PR solve?
- [x] Remove `.DS_Store` file from source code
- [x] Remove `.DS_Store` in **Gemspec** file

### CODE REVIEW

**Comment by norioumata** [comment]
Hi @cb-rakesh, could you please merge this PR?

**Review by cb-dyaneshwaran — CHANGES_REQUESTED** [review]
Perhaps consider updating the .gitignore as well to recursively ignore .DS_Store in the entire repository ?

`**/.DS_Store` should suffice.

**Comment by norioumata** [comment]
@cb-dyaneshwaran, We have already `.DS_Store` in `.gitignore`
And `.DS_Store` is the same as `**/.DS_Store`

**Comment by cb-dyaneshwaran** [comment]
Agreed, @norioumata and the proposed change still serves the purpose. Its just that the standard convention to ignore DS_Stores in a repo completely (recursively in all subdirectories, not only the root dir) is to have `**/.DS_Store` in the .gitignore and we missed it. 

@cb-rakesh, this is a simple change and I dont see any problem in the PR.

**Comment by remy727** [comment]
@cb-rakesh @cb-dyaneshwaran, can we merge this PR?

**Comment by cb-prajaktachavan** [comment]
Closing this PR as it is already fixed.

**Pull request closed without merging**
