### PR TITLE
Added Gemfile and use Bundler

### PR DESCRIPTION
**Pull request by cmer**

### CODE REVIEW

**Comment by dogweather** [comment]
Would it be possible to merge this?

**Comment by evolve2k** [comment]
Maybe silly question, but why are you wanting a Gemfile,  all the gems needed are defined in [chargebee.gemspec](https://github.com/chargebee/chargebee-ruby/blob/master/chargebee.gemspec#L5), no?

**Comment by ball-hayden** [comment]
@evolve2k this is true, but it makes it easier for a contributor to use the correct versions of dependency gems.

**Comment by cb-khushbubibay** [comment]
Thanks @cmer  for raising this PR.
Gemfile has been added in version v2.18.0, hence closing this PR.

**Pull request closed without merging**
